[package]
name = "escrow"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">= 2.6.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.23.0" }

[scripts]
test = "snforge test"

[tool.fmt]
max-line-length = 120
sort-module-level-items = true
