[sncast.sepolia]
# url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
url = "https://free-rpc.nethermind.io/sepolia-juno"
account = "../sepolia_account.json"
keystore = "../sepolia_keystore.json"
